### ISSUE TITLE
Text Edits on Teachings Page

### ISSUE THREAD

**Issue by davidfrost** [atheycreek/atheycreek#54]
https://github.com/atheycreek/atheycreek/blob/5d58bf1c9d51527c0e8f5140df1e824a810f7067/workspace/xsl/teachings.xsl

Line 13 should be:
<p>This page contains every single teaching we have done, ordered by book of the Bible.</p>

Line 61 should be:
<p>This page contains every single teaching tag, ordered alphabetically.</p>

Thank you.

**Comment by jdsimcoe** [comment]
@davidfrost I fixed it! I actually made it smarter. Instead of being in plain text, I stored the values in the backend of Symphony so Athey staff can edit them whenever they want. To edit the values go to [`Misc`](http://atheycreek.com/admin/publish/misc/) and find `teachings-by-book` or `teachings-by-tag`. Or here are the direct links:

- [teachings-by-book](http://atheycreek.com/admin/publish/misc/edit/16809/)
- [teachings-by-tag](http://atheycreek.com/admin/publish/misc/edit/16810/)

**Comment by jdsimcoe** [comment]
@davidfrost Note that I already added your edits so this is for if/when you need to change them in the future.

**Comment by davidfrost** [comment]
Thanks so much!

Congrats on the cute kid too!

On Jan 27, 2016, at 3:06 PM, Jonathan Simcoe <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidfrost<https://github.com/davidfrost> I fixed it! I actually made it smarter. Instead of being in plain text, I stored the values in the backend of Symphony so Athey staff can edit them whenever they want. To edit the values go to Misc<http://atheycreek.com/admin/publish/misc/> and find teachings-by-book or teachings-by-tag. Or here are the direct links:

  *   teachings-by-book<http://atheycreek.com/admin/publish/misc/edit/16809/>
  *   teachings-by-tag<http://atheycreek.com/admin/publish/misc/edit/16810/>
